# Generated by Django 2.0 on 2017-12-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number_of_semesters', models.IntegerField()),
                ('total_number_of_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_program', models.CharField(max_length=60)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Profile.College')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Prefiero no decir')], default='M', max_length=2)),
                ('academicId', models.CharField(max_length=8)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('curp', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn_expiry_date', models.DateField(blank=True, null=True)),
                ('vote_key', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cellphone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('credits_coursed', models.IntegerField(blank=True, null=True)),
                ('credit_percentage_coursed', models.IntegerField(blank=True, null=True)),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.AcademicProgram')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Address')),
                ('languages', models.ManyToManyField(related_name='profile', to='Profile.Language')),
                ('nationality', models.ManyToManyField(related_name='profile', to='Profile.Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('GF', 'Abuelo'), ('GM', 'Abuela'), ('U', 'Tío'), ('A', 'Tía'), ('M', 'Madre'), ('F', 'Padre')], default='F', max_length=2)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Address')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Tutor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Profile.Profile'),
        ),
    ]
