# Generated by Django 2.0 on 2017-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='country',
            field=models.CharField(choices=[('US', 'Estados Unidos de América'), ('CA', 'Canadá'), ('MX', 'México'), ('CU', 'Cuba'), ('RD', 'República Dominicana'), ('CR', 'Costa Rica'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('BR', 'Brasil'), ('BV', 'Bolivia'), ('CH', 'Chile'), ('AR', 'Argentina'), ('UR', 'Uruguay'), ('PO', 'Polonia'), ('SP', 'España'), ('FR', 'Francia'), ('IT', 'Italia'), ('GR', 'Alemania'), ('RC', 'República Checa'), ('HU', 'Hungría'), ('POL', 'Polonia'), ('FIN', 'Finlandia'), ('CH', 'China'), ('IN', 'India'), ('TL', 'Tailandia'), ('CS', 'Corea del Sur')], default='MX', max_length=4),
        ),
    ]
