# Generated by Django 2.0 on 2017-12-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20171209_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', to='Profile.Department'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_types', to='Profile.Language'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Profile.College'),
        ),
    ]
