# Generated by Django 2.0 on 2017-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20171209_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
