# Generated by Django 2.0.1 on 2018-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20180223_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='profile', to='Profile.Language'),
        ),
    ]
