# Generated by Django 2.0.1 on 2018-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20180310_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_percentage_coursed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credits_coursed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
