# Generated by Django 2.0.1 on 2018-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20180314_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
