# Generated by Django 2.0.1 on 2018-04-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_address_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Address'),
        ),
    ]
