# Generated by Django 2.0.1 on 2018-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20180410_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
